import { CityBuildRegistry } from '@civ-clone/core-city-build/CityBuildRegistry';
import { CityGrowthRegistry } from '@civ-clone/core-city-growth/CityGrowthRegistry';
import { CityRegistry } from '@civ-clone/core-city/CityRegistry';
import { GoodyHutRegistry } from '@civ-clone/core-goody-hut/GoodyHutRegistry';
import { LeaderRegistry } from '@civ-clone/core-civilization/LeaderRegistry';
import { PathFinderRegistry } from '@civ-clone/core-world-path/PathFinderRegistry';
import { PlayerGovernmentRegistry } from '@civ-clone/core-government/PlayerGovernmentRegistry';
import { PlayerResearchRegistry } from '@civ-clone/core-science/PlayerResearchRegistry';
import { PlayerTreasuryRegistry } from '@civ-clone/core-treasury/PlayerTreasuryRegistry';
import { PlayerWorldRegistry } from '@civ-clone/core-player-world/PlayerWorldRegistry';
import { RuleRegistry } from '@civ-clone/core-rule/RuleRegistry';
import { TerrainFeatureRegistry } from '@civ-clone/core-terrain-feature/TerrainFeatureRegistry';
import { TileImprovementRegistry } from '@civ-clone/core-tile-improvement/TileImprovementRegistry';
import { UnitImprovementRegistry } from '@civ-clone/core-unit-improvement/UnitImprovementRegistry';
import { UnitRegistry } from '@civ-clone/core-unit/UnitRegistry';
import AIClient from '@civ-clone/core-ai-client/AIClient';
import City from '@civ-clone/core-city/City';
import Player from '@civ-clone/core-player/Player';
import Tile from '@civ-clone/core-world/Tile';
import Unit from '@civ-clone/core-unit/Unit';
export declare class SimpleAIClient extends AIClient {
    #private;
    constructor(player: Player, cityRegistry?: CityRegistry, cityBuildRegistry?: CityBuildRegistry, cityGrowthRegistry?: CityGrowthRegistry, goodyHutRegistry?: GoodyHutRegistry, leaderRegistry?: LeaderRegistry, pathFinderRegistry?: PathFinderRegistry, playerGovernmentRegistry?: PlayerGovernmentRegistry, playerResearchRegistry?: PlayerResearchRegistry, playerTreasuryRegistry?: PlayerTreasuryRegistry, playerWorldRegistry?: PlayerWorldRegistry, ruleRegistry?: RuleRegistry, terrainFeatureRegistry?: TerrainFeatureRegistry, tileImprovementRegistry?: TileImprovementRegistry, unitImprovementRegistry?: UnitImprovementRegistry, unitRegistry?: UnitRegistry);
    scoreUnitMove(unit: Unit, tile: Tile): number;
    moveUnit(unit: Unit): void;
    preProcessTurn(): void;
    takeTurn(): Promise<void>;
    private buildItemInCity;
    cityLost(city: City, player: Player | null, destroyed: boolean): void;
    unitDestroyed(unit: Unit, player: Player | null): void;
}
export default SimpleAIClient;
