import { AvailableSpecialistRegistry } from '@civ-clone/core-city/AvailableSpecialistRegistry';
import { CityBuildRegistry } from '@civ-clone/core-city-build/CityBuildRegistry';
import { CityGrowthRegistry } from '@civ-clone/core-city-growth/CityGrowthRegistry';
import { CityImprovementRegistry } from '@civ-clone/core-city-improvement/CityImprovementRegistry';
import { CityRegistry } from '@civ-clone/core-city/CityRegistry';
import { ClientRegistry } from '@civ-clone/core-client/ClientRegistry';
import { Engine } from '@civ-clone/core-engine/Engine';
import { GoodyHutRegistry } from '@civ-clone/core-goody-hut/GoodyHutRegistry';
import { InteractionRegistry } from '@civ-clone/core-diplomacy/InteractionRegistry';
import { PathFinderRegistry } from '@civ-clone/core-world-path/PathFinderRegistry';
import { PendingEffectRegistry } from '@civ-clone/core-pending-effect';
import { PlayerGovernmentRegistry } from '@civ-clone/core-government/PlayerGovernmentRegistry';
import { PlayerResearchRegistry } from '@civ-clone/core-science/PlayerResearchRegistry';
import { PlayerTradeRatesRegistry } from '@civ-clone/core-trade-rate/PlayerTradeRatesRegistry';
import { PlayerTreasuryRegistry } from '@civ-clone/core-treasury/PlayerTreasuryRegistry';
import { PlayerWorldRegistry } from '@civ-clone/core-player-world/PlayerWorldRegistry';
import { RuleRegistry } from '@civ-clone/core-rule/RuleRegistry';
import { SpecialistRegistry } from '@civ-clone/core-city/SpecialistRegistry';
import { StrategyNoteRegistry } from '@civ-clone/core-strategy/StrategyNoteRegistry';
import { TerrainFeatureRegistry } from '@civ-clone/core-terrain-feature/TerrainFeatureRegistry';
import { TileImprovementRegistry } from '@civ-clone/core-tile-improvement/TileImprovementRegistry';
import { TraitRegistry } from '@civ-clone/core-civilization/TraitRegistry';
import { Turn } from '@civ-clone/core-turn-based-game/Turn';
import { UnitImprovementRegistry } from '@civ-clone/core-unit-improvement/UnitImprovementRegistry';
import { UnitRegistry } from '@civ-clone/core-unit/UnitRegistry';
import { WorkedTileRegistry } from '@civ-clone/core-city/WorkedTileRegistry';
import { MemoryRegistry } from './MemoryRegistry';
export interface Dependencies {
  availableSpecialistRegistry: AvailableSpecialistRegistry;
  cityBuildRegistry: CityBuildRegistry;
  cityGrowthRegistry: CityGrowthRegistry;
  cityImprovementRegistry: CityImprovementRegistry;
  cityRegistry: CityRegistry;
  clientRegistry: ClientRegistry;
  engine: Engine;
  goodyHutRegistry: GoodyHutRegistry;
  interactionRegistry: InteractionRegistry;
  memoryRegistry: MemoryRegistry;
  pathFinderRegistry: PathFinderRegistry;
  pendingEffectRegistry: PendingEffectRegistry;
  playerGovernmentRegistry: PlayerGovernmentRegistry;
  playerResearchRegistry: PlayerResearchRegistry;
  playerTradeRatesRegistry: PlayerTradeRatesRegistry;
  playerTreasuryRegistry: PlayerTreasuryRegistry;
  playerWorldRegistry: PlayerWorldRegistry;
  randomNumberGenerator: () => number;
  ruleRegistry: RuleRegistry;
  specialistRegistry: SpecialistRegistry;
  strategyNoteRegistry: StrategyNoteRegistry;
  terrainFeatureRegistry: TerrainFeatureRegistry;
  tileImprovementRegistry: TileImprovementRegistry;
  traitRegistry: TraitRegistry;
  turn: Turn;
  unitImprovementRegistry: UnitImprovementRegistry;
  unitRegistry: UnitRegistry;
  workedTileRegistry: WorkedTileRegistry;
}
export declare const createDependencies: (
  dependencies?: Partial<Dependencies>
) => Dependencies;
export default Dependencies;
